export const checkboxRow1 = [
  "1M",
  "3M",
  "5M",
  "7M",
  "9M",
  "11M",
  "13M",
  "15M",
  "17M",
];

export const checkboxRow2 = [
  "2M",
  "4M",
  "6M",
  "8M",
  "10M",
  "12M",
  "14M",
  "16M",
  "18M",
];

export const checkboxRow3 = [
  "19W",
  "20W",
  "21W",
  "22W",
  "23W",
  "24W",
  "25W",
  "26W",
  "27W",
];

export const LocationData = [
  {
    id: 1,
    value: "Trichy",
  },
  {
    id: 2,
    value: "Namakkal",
  },
  {
    id: 3,
    value: "Chennai",
  },
  {
    id: 4,
    value: "Madurai",
  },
  {
    id: 5,
    value: "Salem",
  },
  {
    id: 6,
    value: "Erode",
  },
];

export const TravelsData = [
  {
    id: 1,
    name: "Sabari Travles",
    type: "A/C Sleeper",
    route: "Senthamangalam and Salem",
    departureTime24: "04.00",
    departureLocation: "Namakkal",
    duration: "08h 30m",
    arrivalTime24: "13.30",
    arrivalLocation: "Chennai",
    ratings: 4.8,
    ratingCount: 1144,
    fare: 1170,
    noOfSeats: 35,
    singleSeats: 12,
    year: 2023,
    month: "Jul",
    date: "8",
    day: "Sat",
  },
  {
    id: 2,
    name: "Vetri Travles",
    type: "Non A/C Sleeper",
    route: "Senthamangalam and Salem",
    departureTime24: "07.00",
    departureLocation: "Namakkal",
    duration: "07h 30m",
    arrivalTime24: "03.30",
    arrivalLocation: "Chennai",
    ratings: 4.0,
    ratingCount: 944,
    fare: 870,
    noOfSeats: 35,
    singleSeats: 12,
    year: 2023,
    month: "Jul",
    date: "8",
    day: "Sat",
  },
  {
    id: 3,
    name: "Sky Travles",
    type: "Sleeper",
    route: "Senthamangalam and Salem",
    departureTime24: "20.00",
    departureLocation: "Namakkal",
    duration: "07h 30m",
    arrivalTime24: "03.30",
    arrivalLocation: "Chennai",
    ratings: 4.0,
    ratingCount: 944,
    fare: 870,
    noOfSeats: 35,
    singleSeats: 12,
    year: 2023,
    month: "Jul",
    date: "8",
    day: "Sat",
  },
  {
    id: 4,
    name: "SRM Travles",
    type: "NON A/C Sleeper",
    route: "Senthamangalam and Salem",
    departureTime24: " 04.15",
    departureLocation: "Namakkal",
    duration: "08h 30m",
    arrivalTime24: " 13.30",
    arrivalLocation: "Chennai",
    ratings: 4.9,
    ratingCount: 2470,
    fare: 720,
    noOfSeats: 35,
    singleSeats: 12,
    year: 2023,
    month: "Jul",
    date: "8",
    day: "Sat",
  },
  {
    id: 5,
    name: "RRR Travles",
    type: "A/C",
    route: "Senthamangalam and Salem",
    departureTime24: "14.10",
    departureLocation: "Namakkal",
    duration: "08h 30m",
    arrivalTime24: "12.15",
    arrivalLocation: "Chennai",
    ratings: 4.1,
    ratingCount: 1470,
    fare: 570,
    noOfSeats: 35,
    singleSeats: 12,
    year: 2023,
    month: "Jul",
    date: "8",
    day: "Sat",
  },
];
